apiVersion: michelangelo.api/v2
kind: Pipeline
metadata:
  namespace: "california-housing"
  name: "xgb-train"
  annotations:
    michelangelo/uniflow-image: ghcr.io/michelangelo-ai/michelangelo-examples:california-housing
spec:
  type: "PIPELINE_TYPE_TRAIN"
  manifest:
    filePath: michelangelo_examples.california_housing.pipelines.xgb_train.pipeline
